AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM Template for Cities module.'

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: "provided.al2023"
    Architectures:
      - "arm64"

Parameters:
  SpringProfile:
    Type: String
    Default: "dev"
    Description: "Spring profile for the functions."

Resources:
  CitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Cities"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"

  CityDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./city-data-function
      FunctionName: "city-data-function"
      Description: "City Data function used only for internal services."
      Handler: "org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CitiesTable
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref SpringProfile
    Metadata:
      BuildMethod: "makefile"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CityDataFunction}"
      RetentionInDays: 7

Outputs:
  CityDataFunctionArn:
    Description: "City Data function ARN."
    Value: !GetAtt CityDataFunction.Arn

  CitiesTableArn:
    Description: "Cities DynamoDB table ARN."
    Value: !GetAtt CitiesTable.Arn

  CityDataFunctionIamRoleArn:
    Description: "Implicit IAM Role ARN created for the City Data function."
    Value: !GetAtt CityDataFunctionRole.Arn
