name: "hiperium-cities"
services:
  
  city-data-function:
    image: "hiperium/city-data-function:1.0.0"
    container_name: "city-data-function"
    build:
      context: functions/city-data-function
      dockerfile: tools/docker/Dockerfile-native
    ports:
      - "9000:8080"
    env_file:
      - utils/docker/lambda.env
    volumes:
      - cities-volume:/var/tmp
    networks:
      - "cities-network"

  cities-localstack:
    image: "localstack/localstack:latest"
    container_name: "cities-localstack"
    ports:
      - "4566:4566"
    env_file:
      - utils/docker/localstack.env
    volumes:
      - cities-volume:/var/tmp/city-data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./functions/city-data-function/src/test/resources/localstack/table-data.json:/var/lib/localstack/table-data.json
      - ./functions/city-data-function/src/test/resources/localstack/table-setup.sh:/etc/localstack/init/ready.d/1_table-setup.sh
      - ./utils/docker/localstack/lambda-native-setup.sh:/etc/localstack/init/ready.d/2_lambda-setup.sh
    networks:
      - "cities-network"
    depends_on:
      - "city-data-function"

volumes:
  cities-volume:

networks:
  cities-network:
