name: "hiperium-cities"
services:

  city-data-function:
    image: "hiperium/city-data-function:1.0.0"
    container_name: "city-data-function"
    build:
      context: functions
      dockerfile: city-data-function/tools/docker/Dockerfile-native
    ports:
      - "9000:8080"
    env_file:
      - commons/docker-compose/functions.env
    volumes:
      - cities-data:/var/tmp
    networks:
      - "cities-network"

  localstack:
    image: "localstack/localstack:latest"
    container_name: "cities-localstack"
    ports:
      - "4566:4566"
    env_file:
      - commons/docker-compose/localstack.env
    volumes:
      - cities-data:/var/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./functions/city-data-function/src/test/resources/localstack/table-data.json:/var/lib/localstack/table-data.json
      - ./functions/city-data-function/src/test/resources/localstack/table-setup.sh:/etc/localstack/init/ready.d/table-setup.sh
    depends_on:
      - "city-data-function"
    networks:
      - "cities-network"

volumes:
  cities-data:

networks:
  cities-network:
